### ISSUE TITLE
Making fonttools in 64 bit builds

### ISSUE THREAD

**Issue by JaiSoone** [jtanx/fontforgebuilds#10]
I changed into  ~/ff-build/work/mingw64/fontforge/contrib/fonttools
and ran make. I got the one I wanted to build ok.
For the record though, stripttc.c, wolf.c, dewolf.c, and pcl2ttf.c
get an error like this:

 make dewoff
x86_64-w64-mingw32-gcc -DWIN32 -I/home/NateJoe/ff-build/target/mingw64//include -I/mingw64/include -I/usr/local/include -I/include -g -DWIN32 -I/home/NateJoe/ff-build/target/mingw64//include -I/mingw64/include -I/usr/local/include -I/include -g -I../.. -I../.. -L/home/NateJoe/ff-build/target/mingw64//lib -L/mingw64/lib -L/usr/local/lib -L/lib -lws2_32  dewoff.c   -o dewoff
dewoff.c:8:10: fatal error: tottf.h: No such file or directory
 #include "tottf.h"
          ^~~~~~~~~
compilation terminated.
make: *** [<builtin>: dewoff] Error 1

Note also that documentation on https://fontforge.github.io/en-US/documentation/utilities/
I found misleading as it takes one to sourceforge which shows fontforge and fonttools at the same directory level (at least that is the way I took it), but on GitHub the fonttools are actually in contrib/fonttools. A reasonable place, but for a novice like me, I had a hard time finding them.
I thought for a while that they had just gotten dropped in the move to GitHub.

**Comment by jtanx** [comment]
From what I understand, anything under `contrib` is somewhat unmaintained. The issue that you ran into is not specific to Windows/ffbuild, but is a problem of the fontforge build system itself. Ideally this should be tracked on FontForge's [issue tracker](https://github.com/fontforge/fontforge/issues) instead of here.

In any case, this appears to be the result of some headers being moved around. I've found that at least for `dewoff.c`, commenting out the include for `tottf.h` and `mem.h` allows it to compile without errors.

**Comment by JaiSoone** [comment]
Yah, it's kind of old, and from what I can see the parsing of the cmap table is far more advanced in fontforge. I'll come back to this later.
