### ISSUE TITLE
Why can I only import fontforge after "cd bin" ?

### ISSUE THREAD

**Issue by alexaschee** [jtanx/fontforgebuilds#8]
I can't import fontforge after running `fontforge-console.bat` and `ffpython,` so I added `FontForgeBuilds/bin` to my `PYTHONPATH`

![image](https://user-images.githubusercontent.com/13317191/27132574-edb6346a-5141-11e7-957c-a3f1c0b0f52a.png)

I don't want to cd bin every time. How to fix this? Oh, I'm on Windows 10 pro.

**Comment by jtanx** [comment]
Strange, I can't reproduce this. Is this a clean install?

```
D:\FontForgeBuilds>ffpython
Python 2.7.12 (default, Sep 24 2016, 09:26:33)  [GCC 6.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fontforge
>>> fontforge.__file__
'D:\\FontForgeBuilds\\lib\\python2.7\\site-packages/fontforge.pyd'
>>> import sys
>>> sys.path
['', 'D:\\FontForgeBuilds\\lib\\python2.7', 'D:\\FontForgeBuilds\\lib\\python27.zip', 'D:\\FontForgeBuilds\\lib\\python2.7\\plat-win32', 'D:\\FontForgeBuilds\\lib\\python2.7\\lib-tk', 'D:\\FontForgeBuilds\\lib\\python2.7\\lib-old', 'D:\\FontForgeBuilds\\lib\\python2.7\\lib-dynload', 'C:\\building\\msys64\\mingw32', 'D:\\FontForgeBuilds\\lib\\python2.7\\site-packages']
>>>
```

**Comment by alexaschee** [comment]
Turns out there're 2 fontforge.pyd (different file size): the smaller one in `D:\FontForgeBuilds\bin` and the other in `D:\FontForgeBuilds\lib\\python2.7\site-packages`.

I removed the bin one and tried to import fontforge and failed.

So I uninstalled and reinstalled. This time everything is by default and I got only one fontforge.pyd in `D:\FontForgeBuilds\lib\\python2.7\site-packages`, but still, import fails unless the current path is `D:\FontForgeBuilds\lib\\python2.7\site-packages`.

Since ffpython comes in with fontforge, other pythons on my machine would not  have any effect on this, I guess?

**Comment by jtanx** [comment]
> Since ffpython comes in with fontforge, other pythons on my machine would not have any effect on this, I guess?

It shouldn't, as far as I know.

what does:

```cmd
echo %FF%
echo %PYTHONHOME%
echo %PYTHONPATH%
echo %PATH%
```

Produce from the fontforge console? These are all set/modified by `fontforge-console.bat` -  the `PYTHONPATH` environment variable is what should allow `fontforge` to be imported from anywhere, irrespective of your current folder.

**Comment by alexaschee** [comment]
d:\FontForgeBuilds>echo %FF%
D:\FontForgeBuilds\

d:\FontForgeBuilds>echo %PYTHONHOME%
D:\FontForgeBuilds\

d:\FontForgeBuilds>echo %PYTHONPATH%
D:\FontForgeBuilds\lib\python2.7

d:\FontForgeBuilds>echo %PATH%
D:\FontForgeBuilds\;D:\FontForgeBuilds\\bin;C:\ProgramData\Oracle\Java\javapath;c:\Program Files\Java\jre1.8.0_111\bin;D:\Python3;D:\Python3\Scripts;e:\msys32\mingw32\bin;e:\msys32\usr\bin;e:\ctags;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\rust\bin

d:\FontForgeBuilds>`

**Comment by jtanx** [comment]
Hmm... Thinking about this some more, it looks more like either that a required DLL that fontforge.pyd depends on can't be found, or due to your search path, it's loading the wrong DLL from some other folder.

Unfortunately, I don't really have an easy way to reproduce this on my side. To know what is happening, the steps are:

* Download and extract dependency walker: http://www.dependencywalker.com/depends22_x86.zip (get the 32-bit version; I've linked to this)
* This part is important; it sets the `PATH` environment variable: From the fontforge console, launch dependency walker, e.g.:

```
Configuring the system path to add FontForge...
Configuration complete. You can now call 'fontforge' from the console.
You may also use the bundled Python distribution by calling `ffpython`.
Extra Python modules that you require may be installed via `ffpython`.

D:\FontForgeBuilds>D:\depends22_x86\depends.exe
```

* From dependency walker, open `fontforge.pyd` from `D:\FontForgeBuilds\lib\python2.7\site-packages`
* In dependency walker, go to the menu: `View->Full Paths`
* ![depends](https://user-images.githubusercontent.com/5137410/27247998-818f8da2-5341-11e7-9a37-11f4faf46a2a.png)

* Try to look for anything in the left hand pane where the icon is either a question mark (as above), or is coloured red. Also look for anything where the path isn't `D:\fontforgebuilds\bin` or `C:\windows\system32` (except as described in the next point). In the right hand pane, the thing to look out for is a red icon in the `PI` column. 
* Generally, DLLs like `KERNEL32.DLL`, `USER32.DLL`, `WS2_32.DLL`, `MSVCRT.DLL` can all be ignored, as these are all standard system DLLs. Things to be wary of include custom DLLs in system folders, e.g. `zlib1.dll` under `C:\Windows\System32`.

**Comment by alexaschee** [comment]
Thanks for your tip, @jtanx.

Again, it's zlib1.dll. Different versions of zlib1.dll have caused me much trouble. For different applications I have to copy different zlib1 into system32.

This time I copied the one from FontForgeBuilds/bin, and then I could import fontforge.

Thanks again.

**Comment by jtanx** [comment]
Glad you found a solution @alexaschee. However, I would recommend against having any `zlib1.dll` in `C:\Windows\System32` or `C:\Windows\SysWOW64` if possible, as this would affect all applications that rely on zlib (quite a few!). This is because system32\syswow64 has higher precedence in the search order, making it very difficult to use the correct zlib dll that comes with each software package.
